In [1]:
import yfinance

In [2]:
btc_usd = yfinance.Ticker('BTC-USD')

In [11]:
hist = btc_usd.history(period='1mo', interval='1h')

In [12]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2023-03-09 12:00:00+00:00,21674.878906,21679.451172,21621.976562,21625.052734,0,0.0,0.0
2023-03-09 13:00:00+00:00,21624.003906,21720.484375,21588.546875,21709.763672,336490496,0.0,0.0
2023-03-09 14:00:00+00:00,21710.484375,21796.121094,21702.820312,21718.710938,146388992,0.0,0.0
2023-03-09 15:00:00+00:00,21720.011719,21777.724609,21668.378906,21669.142578,0,0.0,0.0
2023-03-09 16:00:00+00:00,21668.062500,21669.951172,21506.064453,21515.781250,650418176,0.0,0.0
...,...,...,...,...,...,...,...
2023-04-09 08:00:00+00:00,27920.966797,27938.755859,27847.158203,27895.812500,73183232,0.0,0.0
2023-04-09 09:00:00+00:00,27897.750000,27947.687500,27896.910156,27909.824219,6253568,0.0,0.0
2023-04-09 10:00:00+00:00,27914.250000,27925.875000,27892.849609,27892.865234,0,0.0,0.0
2023-04-09 11:00:00+00:00,27902.494141,27947.484375,27883.878906,27947.484375,85991424,0.0,0.0
2023-04-09 12:00:00+00:00,27947.794922,27979.201172,27938.392578,27979.201172,85074944,0.0,0.0

In [13]:
btc_usd.history_metadata

{'currency': 'USD',
 'symbol': 'BTC-USD',
 'exchangeName': 'CCC',
 'instrumentType': 'CRYPTOCURRENCY',
 'firstTradeDate': 1410912000,
 'regularMarketTime': 1681043460,
 'gmtoffset': 0,
 'timezone': 'UTC',
 'exchangeTimezoneName': 'UTC',
 'regularMarketPrice': 27979.201,
 'chartPreviousClose': 20363.021,
 'previousClose': 27946.512,
 'scale': 3,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'UTC',
   'start': 1680998400,
   'end': 1680998400,
   'gmtoffset': 0},
  'regular': {'timezone': 'UTC',
   'start': 1680998400,
   'end': 1681084740,
   'gmtoffset': 0},
  'post': {'timezone': 'UTC',
   'start': 1681084740,
   'end': 1681084740,
   'gmtoffset': 0}},
 'tradingPeriods': [[{'timezone': 'UTC',
    'start': 1678320000,
    'end': 1678406340,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1678406400,
    'end': 1678492740,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1678492800,
    'end': 1678579140,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1678579200,
    'end': 1678665540,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1678665600,
    'end': 1678751940,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1678752000,
    'end': 1678838340,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1678838400,
    'end': 1678924740,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1678924800,
    'end': 1679011140,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679011200,
    'end': 1679097540,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679097600,
    'end': 1679183940,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679184000,
    'end': 1679270340,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679270400,
    'end': 1679356740,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679356800,
    'end': 1679443140,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679443200,
    'end': 1679529540,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679529600,
    'end': 1679615940,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679616000,
    'end': 1679702340,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679702400,
    'end': 1679788740,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679788800,
    'end': 1679875140,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679875200,
    'end': 1679961540,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1679961600,
    'end': 1680047940,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680048000,
    'end': 1680134340,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680134400,
    'end': 1680220740,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680220800,
    'end': 1680307140,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680307200,
    'end': 1680393540,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680393600,
    'end': 1680479940,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680480000,
    'end': 1680566340,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680566400,
    'end': 1680652740,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680652800,
    'end': 1680739140,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680739200,
    'end': 1680825540,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680825600,
    'end': 1680911940,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680912000,
    'end': 1680998340,
    'gmtoffset': 0}],
  [{'timezone': 'UTC',
    'start': 1680998400,
    'end': 1681084740,
    'gmtoffset': 0}]],
 'dataGranularity': '1h',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [ ]:
unable = yfinance.Ticker('UUSNNF')

In [16]:
unable.hist

yfinance.Ticker object <UUSNNF>